### ISSUE TITLE
Meteor 0.6.5

### ISSUE THREAD

**Issue by ryw** [project-ricochet/meteor-canonical#2]
I get this error when Meteor boots up

```
W20130824-13:24:13.244(-4)? (STDERR) /Users/ry/.meteor/tools/4010e5731d/lib/node_modules/fibers/future.js:173
W20130824-13:24:13.244(-4)? (STDERR)                        throw(ex);
W20130824-13:24:13.244(-4)? (STDERR)                              ^
W20130824-13:24:13.249(-4)? (STDERR) TypeError: Cannot call method 'listeners' of undefined
W20130824-13:24:13.250(-4)? (STDERR)     at packages/meteor-canonical/canonical_server.js:12
W20130824-13:24:13.250(-4)? (STDERR)     at packages/meteor-canonical.js:107:4
W20130824-13:24:13.250(-4)? (STDERR)     at packages/meteor-canonical.js:114:3
W20130824-13:24:13.250(-4)? (STDERR)     at mains (/Users/ry/code/cintrifuse/.meteor/local/build/programs/server/boot.js:153:10)
W20130824-13:24:13.251(-4)? (STDERR)     at Array.forEach (native)
W20130824-13:24:13.251(-4)? (STDERR)     at Function._.each._.forEach (/Users/ry/.meteor/tools/4010e5731d/lib/node_modules/underscore/underscore.js:79:11)
W20130824-13:24:13.251(-4)? (STDERR)     at /Users/ry/code/cintrifuse/.meteor/local/build/programs/server/boot.js:80:5
```

**Comment by wizonesolutions** [comment]
Thanks for the report.

Yeah, the package system changed in 0.6.5. I think `meteor-canonical`'s `package.js` needs to explicitly use the packages it's using...probably `webapp`.

Will try to take a look during the week. Pull request welcome if you work it out.

**Comment by ryw** [comment]
Pull request: https://github.com/project-ricochet/meteor-canonical/pull/3
